### ISSUE TITLE
Jest v27 incompatible?

### ISSUE THREAD

**Issue by patrickhousley** [eduter/screeps-jest#20]
When running with jest@27.1.0 and ts-jest@27.0.5, the below error is thrown.

```shell
    TypeError: Cannot read property 'fn' of undefined

      at Object.mockRoomPositionConstructor (node_modules/screeps-jest/src/mocking.js:133:53)
      at TestEnvironment.setup (node_modules/screeps-jest/src/TestEnvironment.js:13:19)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:261:3)
```

**Comment by eduter** [comment]
Yeah, someone already pointed that out in Discord a while ago. Apparently, there was a breaking change in Jest v27, but I haven't looked into it yet. Thanks for creating a ticket for it 👍
